In [31]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import time
import seaborn as sns 
from sklearn.externals import joblib
from sklearn.metrics import  classification_report, confusion_matrix

In [72]:
data = pd.read_csv('../output/feature_extraction_test.csv')

In [73]:
data = data.drop(columns=['Unnamed: 0'])
X = data.values

In [52]:
# X,y = data[:,:6006],data[:,6006]

## GBM baseline

In [74]:

gbm_model = joblib.load('../output/gbm_base.m')
start_time = time.time()
gbm_predictions=gbm_model.predict(X)
print("--- %s seconds ---" % (time.time() - start_time))
# np.mean(gbm_predictions==y)
# cn = confusion_matrix(y,gbm_predictions)
# sns.heatmap(cn)
# print(classification_report(y,gbm_predictions))
# from sklearn.metrics import accuracy_score
# gbm_predictions = [round(value) for value in gbm_predictions]
# gbm_accuracy = accuracy_score(y, gbm_predictions)
# print("Accuracy: %.2f%%" % (gbm_accuracy * 100.0))

--- 0.4846048355102539 seconds ---


In [76]:
gbm_predictions

array([12, 17,  9, ...,  4, 14, 19], dtype=int64)

In [75]:
pd.DataFrame(gbm_predictions).to_csv('../output/gbm_predictions.csv')

## SVM 

In [77]:
svm_model = joblib.load('../output/svm.m')
start_time=time.time()
svm_predictions=svm_model.predict(X)
print("--- %s seconds ---" % (time.time() - start_time))
# cn = confusion_matrix(y,svm_predictions)
# sns.heatmap(cn)
# print(classification_report(y,svm_predictions))
# from sklearn.metrics import accuracy_score
# svm_predictions = [round(value) for value in svm_predictions]
# svm_accuracy = accuracy_score(y, svm_predictions)
# print("Accuracy: %.2f%%" % (svm_accuracy * 100.0))

--- 84.39038395881653 seconds ---


In [78]:
svm_predictions

array([22, 18,  9, ...,  4, 20, 18], dtype=int64)

In [79]:
pd.DataFrame(svm_predictions).to_csv('../output/svm_predictions.csv')

## Neural Network

In [81]:
nn_model = joblib.load('../output/nn.m')
start_time=time.time()
nn_predictions=nn_model.predict(X)
print("--- %s seconds ---" % (time.time() - start_time))
nn_predictions = nn_predictions.argmax(axis=-1)
nn_predictions = nn_predictions+1 

--- 1.1881415843963623 seconds ---


In [82]:
nn_predictions

array([22, 17,  9, ...,  4,  7, 19], dtype=int64)

In [83]:
pd.DataFrame(nn_predictions).to_csv('../output/nn_predictions.csv')

In [53]:
# np.mean(nn_predictions==y)

0.9028